REVISION: 1
RELEASED: Thu Jul  4 12:58:35 2019
CHART: cert-manager-0.2.2
USER-SUPPLIED VALUES:
createCustomResource: false

COMPUTED VALUES:
createCustomResource: false
extraArgs: []
image:
  pullPolicy: IfNotPresent
  repository: registry.cn-beijing.aliyuncs.com/quayio/cert-manager-controller 
  tag: v0.2.3
ingressShim:
  enabled: true
  extraArgs: []
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-beijing.aliyuncs.com/quayio/cert-manager-ingress-shim
  resources: {}
nodeSelector: {}
rbac:
  create: true
replicaCount: 1
resources: {}
serviceAccount:
  create: true
  name: null

HOOKS:
MANIFEST:

---
# Source: cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-0.2.2
    release: cert-manager
    heritage: Tiller
---
# Source: cert-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-0.2.2
    release: cert-manager
    heritage: Tiller
rules:
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "issuers", "clusterissuers"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets", "events", "endpoints", "services", "pods"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
---
# Source: cert-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-0.2.2
    release: cert-manager
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cert-manager
subjects:
  - name: cert-manager-cert-manager
    namespace: "kube-system"
    kind: ServiceAccount
---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager-cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-0.2.2
    release: cert-manager
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cert-manager
        release: cert-manager
    spec:
      serviceAccountName: cert-manager-cert-manager
      containers:
        - name: cert-manager
          image: "registry.cn-beijing.aliyuncs.com/quayio/cert-manager-controller:v0.2.3"
          imagePullPolicy: IfNotPresent
          resources:
            {}
            
        - name: ingress-shim
          image: "registry.cn-beijing.aliyuncs.com/quayio/cert-manager-ingress-shim:v0.2.3"
          imagePullPolicy: IfNotPresent
          resources:
            {}
